name: finalproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # UI & Charts
  fl_chart: ^0.66.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700