// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
/// ``` 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhIdLRupXNTtggVAxK1XEjPmeo81lmsQ',
    appId: '1:910907428737:android:68db799a0621022a54e280',
    messagingSenderId: '910907428737',
    projectId: 'masroufy-app',
    storageBucket: 'masroufy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATL8HFMmnXLg9yASQVuM5zkDra8WxR2mw',
    appId: '1:910907428737:ios:f9e122058853f34e54e280',
    messagingSenderId: '910907428737',
    projectId: 'masroufy-app',
    storageBucket: 'masroufy-app.firebasestorage.app',
    androidClientId: '910907428737-um3pedijn502khuus6g4u1vjhkdddbj2.apps.googleusercontent.com',
    iosClientId: '910907428737-1mta0k9954pmhkh8grasuf9m7d4b5k6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6SSYoVIP202vZgCplEGgLg5pfJt8J9Gs',
    appId: '1:910907428737:web:4962a183274a765254e280',
    messagingSenderId: '910907428737',
    projectId: 'masroufy-app',
    authDomain: 'masroufy-app.firebaseapp.com',
    storageBucket: 'masroufy-app.firebasestorage.app',
    measurementId: 'G-W339DGNKP6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATL8HFMmnXLg9yASQVuM5zkDra8WxR2mw',
    appId: '1:910907428737:ios:f9e122058853f34e54e280',
    messagingSenderId: '910907428737',
    projectId: 'masroufy-app',
    storageBucket: 'masroufy-app.firebasestorage.app',
    androidClientId: '910907428737-um3pedijn502khuus6g4u1vjhkdddbj2.apps.googleusercontent.com',
    iosClientId: '910907428737-1mta0k9954pmhkh8grasuf9m7d4b5k6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6SSYoVIP202vZgCplEGgLg5pfJt8J9Gs',
    appId: '1:910907428737:web:908cafb5b56625b354e280',
    messagingSenderId: '910907428737',
    projectId: 'masroufy-app',
    authDomain: 'masroufy-app.firebaseapp.com',
    storageBucket: 'masroufy-app.firebasestorage.app',
    measurementId: 'G-7NVXW4GW6F',
  );

}